version: '3.9'

services:
  webserver:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - minha-rede
  
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
    ports:
      - "3306:3306"
    networks:
      - minha-rede
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - minha-rede


networks:
  minha-rede:
    driver: bridge



  
    